import React from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Bell, CalendarDays, Clock3, Droplets, HeartHandshake, MapPin, Phone, ShieldAlert, Users } from 'lucide-react';
import { mockActivityFeed, mockNews, mockEvents, emergencyContacts } from '../data/mockData';
import { format } from 'date-fns';
import { ImageWithFallback } from '../components/ui/ImageWithFallback';

const fade = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0, transition: { duration: .45 } } };

export default function Home() {
  const event = mockEvents[0];
  return (
    <div className="min-h-screen overflow-hidden bg-[#f5f7f4] text-[#10251e]">
      <section className="relative overflow-hidden bg-[#09251c] text-white">
        <div className="absolute -right-28 -top-40 h-[520px] w-[520px] rounded-full bg-[#3f8769]/25 blur-3xl" />
        <div className="absolute -bottom-52 left-1/3 h-[420px] w-[420px] rounded-full bg-[#d8aa37]/15 blur-3xl" />
        <div className="relative mx-auto max-w-7xl px-5 pb-20 pt-28 sm:px-8 lg:px-10 lg:pb-28 lg:pt-36">
          <div className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20">
            <motion.div initial="hidden" animate="visible" variants={fade}>
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold text-[#f3ca63] backdrop-blur"><span className="h-2 w-2 rounded-full bg-[#f3ca63]" /> Jawkhela · Buner, KPK</div>
              <h1 className="max-w-2xl font-serif text-5xl font-medium leading-[.98] tracking-[-.04em] sm:text-7xl lg:text-[86px]">A stronger<br /><span className="text-[#edc35c]">community,</span><br />together.</h1>
              <p className="mt-7 max-w-xl text-base leading-7 text-white/65 sm:text-lg">A shared space for mutual support, local action, and the people who make Jawkhela home.</p>
              <div className="mt-9 flex flex-wrap gap-3"><Link to="/membership" className="inline-flex items-center gap-2 rounded-xl bg-[#edc35c] px-5 py-3.5 text-sm font-bold text-[#09251c] transition hover:-translate-y-0.5 hover:bg-[#f5d77e]">Join the community <ArrowUpRight size={16} /></Link><Link to="/donations" className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/5 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">Support our work <ArrowRight size={16} /></Link></div>
              <div className="mt-12 flex items-center gap-3 text-xs text-white/55"><span className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#09251c] bg-[#d8b96a] text-[#09251c]">J</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#09251c] bg-[#6ea98c] text-[#09251c]">B</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#09251c] bg-[#f0eee1] text-[#09251c]">+</span></span>Built by neighbors,<br /><b className="text-white">for neighbors.</b></div>
            </motion.div>
            <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .15 }} className="relative">
              <div className="relative h-[390px] overflow-hidden rounded-[28px] border border-white/20 shadow-2xl sm:h-[470px]"><img src="https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&q=85&w=1200" alt="Green mountain landscape around Jawkhela" className="h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#09251c] via-transparent to-transparent" /><div className="absolute bottom-6 left-6"><div className="flex items-center gap-2 text-sm font-semibold"><MapPin size={15} className="text-[#edc35c]" /> Jawkhela, Buner</div><p className="mt-1 pl-6 text-xs text-white/55">Where our shared story begins</p></div></div>
              <div className="absolute -bottom-5 -left-5 rounded-2xl border border-white/15 bg-[#163d2d]/90 p-4 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#edc35c]/15 p-2 text-[#edc35c]"><ShieldAlert size={19} /></div><div><p className="text-xs font-bold">Community first</p><p className="mt-1 text-[10px] text-white/55">Our shared promise</p></div></div></div>
            </motion.div>
          </div>
        </div>
      </section>

      <main className="mx-auto max-w-7xl space-y-24 px-5 pb-20 sm:px-8 lg:px-10">
        <motion.section initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} variants={fade} className="-mt-10 grid gap-4 sm:grid-cols-3">
          {[{ title: 'Membership', desc: 'Stay connected to the community.', icon: Users, href: '/membership', tone: 'bg-blue-50 text-blue-600' }, { title: 'Donations', desc: 'Back projects that matter locally.', icon: HeartHandshake, href: '/donations', tone: 'bg-amber-50 text-amber-600' }, { title: 'Blood Bank', desc: 'Find emergency donors quickly.', icon: Droplets, href: '/blood-bank', tone: 'bg-red-50 text-red-600' }].map(({ title, desc, icon: Icon, href, tone }, i) => <Link to={href} key={title} className="group rounded-2xl border border-[#dfe8e1] bg-white p-5 shadow-[0_18px_40px_-28px_rgba(12,55,38,.5)] transition hover:-translate-y-1 hover:border-[#b8cfbd] hover:shadow-xl"><div className="flex items-start justify-between"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon size={21} /></span><span className="text-xs text-[#9baaa2]">0{i + 1}</span></div><h2 className="mt-5 font-serif text-2xl font-medium">{title}</h2><p className="mt-1 text-sm text-[#718079]">{desc}</p><span className="mt-6 flex items-center gap-1 text-xs font-bold text-[#1e774f]">Explore <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></Link>)}
        </motion.section>

        <section className="grid gap-12 lg:grid-cols-[1.45fr_.75fr]">
          <div className="space-y-16">
            <section><div className="mb-7 flex items-end justify-between border-b border-[#dbe5dd] pb-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#c08d22]">From the field</p><h2 className="mt-2 font-serif text-4xl font-medium tracking-tight sm:text-5xl">Community <span className="text-[#1e774f]">in motion.</span></h2></div><span className="hidden text-xs text-[#718079] sm:block">Recent efforts and fieldwork</span></div><div className="grid gap-5 sm:grid-cols-2">{mockActivityFeed.map((activity) => <article key={activity.id} className="overflow-hidden rounded-2xl border border-[#dfe8e1] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="aspect-[4/3] overflow-hidden bg-[#e6eee8]"><ImageWithFallback src={activity.imageUrl} alt="Community activity" className="h-full w-full" /></div><div className="p-5"><p className="font-medium leading-6 text-[#20362d]">{activity.description}</p><p className="mt-3 text-[11px] font-bold uppercase tracking-wider text-[#9aa9a1]">{format(new Date(activity.date), 'MMM dd, yyyy')}</p></div></article>)}</div></section>
            <section><div className="mb-7 flex items-end justify-between border-b border-[#dbe5dd] pb-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#c08d22]">Stay informed</p><h2 className="mt-2 font-serif text-4xl font-medium tracking-tight sm:text-5xl">Latest <span className="text-[#1e774f]">news.</span></h2></div><Link to="/news" className="flex items-center gap-1 rounded-lg bg-[#eaf4ed] px-3 py-2 text-xs font-bold text-[#1e774f]">View all <ArrowRight size={14} /></Link></div><div className="space-y-3">{mockNews.slice(0, 3).map((news) => <article key={news.id} className="group flex gap-4 rounded-2xl border border-[#dfe8e1] bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><span className="h-fit rounded-lg bg-[#f4f7f4] px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-wide text-[#638071]">{news.category}</span><div className="min-w-0 flex-1"><h3 className="font-serif text-xl font-medium text-[#193329] group-hover:text-[#1e774f]">{news.titleUrdu || news.title}</h3><p className="mt-1 text-sm leading-6 text-[#718079]" dir="auto">{news.descriptionUrdu || news.description}</p><div className="mt-3 flex items-center gap-3 text-[11px] text-[#9aa9a1]"><span>{format(new Date(news.date), 'MMMM dd, yyyy')}</span>{news.comments.length > 0 && <span className="flex items-center gap-1"><Bell size={12} /> {news.comments.length} response</span>}</div></div></article>)}</div></section>
          </div>

          <aside className="space-y-5">
            {event && <div className="rounded-3xl bg-[#10382a] p-7 text-white shadow-xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#edc35c]"><CalendarDays size={15} /> Upcoming event</div><h3 className="mt-8 font-serif text-4xl font-medium leading-tight">{event.title}</h3><div className="mt-7 space-y-3 text-sm text-white/65"><p className="flex items-center gap-3"><Clock3 size={16} className="text-[#edc35c]" /> {format(new Date(event.date), 'PPP')}</p><p className="flex items-center gap-3"><MapPin size={16} className="text-[#edc35c]" /> {event.location}</p></div><Link to="/events" className="mt-8 flex items-center justify-between rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#10382a] transition hover:bg-[#edc35c]">View event details <ArrowUpRight size={16} /></Link></div>}
            <div className="rounded-3xl border border-[#dfe8e1] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-serif text-2xl font-medium">Prayer timings</h3><Clock3 size={18} className="text-[#c08d22]" /></div><div className="mt-5 space-y-1 text-sm">{[['Fajr', '04:15 AM'], ['Dhuhr', '12:15 PM'], ['Asr', '05:00 PM'], ['Maghrib', '07:10 PM'], ['Isha', '08:45 PM']].map(([name, time]) => <div key={name} className={`flex justify-between rounded-xl px-3 py-2.5 ${name === 'Maghrib' ? 'bg-amber-50 font-bold text-amber-800' : 'text-[#718079]'}`}><span>{name}{name === 'Maghrib' && <span className="ml-2 inline-block h-1.5 w-1.5 rounded-full bg-amber-500" />}</span><span>{time}</span></div>)}</div></div>
            <div className="rounded-3xl border border-red-100 bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 font-serif text-2xl font-medium"><ShieldAlert size={19} className="text-red-500" /> Emergency contacts</h3><div className="mt-4 space-y-2">{emergencyContacts.map((contact) => <a key={contact.name} href={`tel:${contact.phone}`} className="flex items-center justify-between rounded-xl p-3 transition hover:bg-red-50"><span><b className="block text-xs text-[#20362d]">{contact.name}</b><small className="text-[10px] text-[#9aa9a1]">Available locally</small></span><span className="flex items-center gap-1 text-[11px] font-bold text-red-500"><Phone size={13} /> Call</span></a>)}</div></div>
          </aside>
        </section>
      </main>
    </div>
  );
}
